### HYPOTHESIS TESTING

### Bombay hospitality Ltd. operates a franchise model for producing exotic Norwegian dinners throughout New England. The operating cost for a franchise in a week (W) is given by the equation W = $1,000 + $5X, where X represents the number of units produced in a week. Recent feedback from restaurant owners suggests that this cost model may no longer be accurate, as their observed weekly operating costs are higher

#### •	The theoretical weekly operating cost model: W = $1,000 + $5X   (dollars)
#### •	Sample of 25 restaurants with a mean weekly cost of Rs. 3,050
#### •	Number of units produced in a week (X) follows a normal distribution with a mean (μ) of 600 units and a standard deviation (σ) of 25 units

## Hypothesis Stating

### h0 - Weekly operating costs μ0 <= μ cost model
### h1 - weekly operating cost μ0 > μ cost model

## Calculate test statistic

### It will be one sample right tailed T - test

#### From the given data,
#### we know sample size n = 25 (<30) we use { T - distribution }
#### sample mean = 3050 (rupees)
#### mean cost = 600 units in terms of w = 1000 + 5 * 600 = 4000(dollars)
#### population standard deviation (w)= 25 * 5

In [109]:
n = 25
sample_mean = (3050/86) # 1 dollar = 86 approx
std = 25 * 5
theo_mean = 1000 + 4*600

In [114]:
t_val = np.round((sample_mean-theo_mean)/(std/np.sqrt(n)),2)

In [118]:
print(f"{t_val} is the test statistic value")

-134.58 is the test statistic value

### T critical Value

#### we know df = n - 1
#### given alpha  = 0.05 (significance value)
#### As it is a right tailed test alpha stays the same

In [119]:
t_crit = np.round(stats.t.ppf(1-0.05,df = 24),2)
print(f"the t - critical value is {t_crit} ")

the t - critical value is 1.71

## Decision

In [122]:
print("Decision \n")
if(t_val < t_crit):
    print("Fail to reject NULL hypothesis")

else:
    print("Reject NULL hypothesis")

Decision

Fail to reject NULL hypothesis

## Conclusion

### As we are here to produce evidence the restaurant owners claim stating that weekly operated cost is higher 
### The test statistic (evidence) showing there is no hike in operating cost. 
### we can follow the cost model as usual.
### we can state without performing any test statistic beacuse the theortical mean showing whopping 4000 dollars, where as the sample restaurant mean showing
### 3050 rupees which is way less than the cost model.

# Chi-square Test

### Mizzare Corporation has collected data on customer satisfaction levels for two types of smart home devices: Smart Thermostats and Smart Lights. They want to determine if there's a significant association between the type of device purchased and the customer's satisfaction level.

### CHI-SQUARE TEST

#### Import the packages

In [ ]:
import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency,chi2

#### Load the data

In [86]:
df = pd.read_csv(r"C:\Users\lrban\Desktop\BTR\DATA SCIENCE\Assignments\Hypothesis testing\df.tsv",sep = "\t",index_col=None)
df

       Satisfaction  Smart Thermostat  Smart Light  Total
0    Very Satisfied                50           70    120
1         Satisfied                80          100    180
2           Neutral                60           90    150
3       Unsatisfied                30           50     80
4  Very Unsatisfied                20           50     70
5             Total               240          360    600

In [87]:
df.set_index(df["Satisfaction"],inplace = True)

In [88]:
df = df.iloc[:df.shape[0] - 1,1:3]

In [89]:
df

                  Smart Thermostat  Smart Light
Satisfaction
Very Satisfied                  50           70
Satisfied                       80          100
Neutral                         60           90
Unsatisfied                     30           50
Very Unsatisfied                20           50

In [90]:
df.shape

(5, 2)

### Stating the hypothesis

#### Mizzare Corporation has collected data on customer satisfaction levels for two types of smart home devices: Smart Thermostats and Smart Lights. 
#### They want to determine if there's a significant association between the type of device purchased and the customer's satisfaction level.

#### h0 = device purchased and the customer's satisfaction level are independent
#### h1 = device purchased and the customer's satisfaction level are not independent

In [105]:
chi_stat,p_value,dof,expected = chi2_contingency(df) #chi2_contingency is method which return all the required values
                                                     # Those are test -statistic , p- value, degrees of freedom, and the expected values matrix
                                                     # pass only one parameter which the data frame.

In [107]:
print(f"""Test statistic is : {np.round(chi_stat,2)}

p-value : {np.round(p_value,2)}

degree of freedom : {dof} 

array of expected values : 

{expected}""" )

Test statistic is : 5.64

p-value : 0.23

degree of freedom : 4

array of expected values :

[[ 48.  72.]
 [ 72. 108.]
 [ 60.  90.]
 [ 32.  48.]
 [ 28.  42.]]

### Critical Value

#### given significance level (alpha) of 0.05 
#### df = (rows -1) * (columns - 1)
#### df = (2 -1) * (5-1)
#### df = 4

In [123]:
from scipy import stats
critical_value = np.round(stats.chi2.ppf(0.95,df = 4),2)

In [124]:
critical_value

9.49

### Decision

#### Based on the above calculation, we obtained test statistic value which is 5.63 . Also using the significance level and degrees of freedom
#### we obtained critical value too which is 9.48 .

In [108]:
print(f"Decision : \n")
if(chi_stat < critical_value):
    print("Failed to reject NULL hypothesis")
else:
    print("Reject NULL hypothesis")

Decision :

Failed to reject NULL hypothesis

#### The chi - square distribution curve is right skewed, so the critical value based on signnificance value and degrees of freedom, lie on the right side. 
#### as the obtained statiscal test value less than the critical value, which is in the region, Obviously null hypothesis cannot be rejected

### we can say device purchased and customer satisfaction are independent